<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>MemeMomo.Program</StartupObject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <AssemblyName>MemeMomo</AssemblyName>
    <RootNamespace>MemeMomo</RootNamespace>
    <Version>0.0.1</Version>
    <Title>MemeMomo</Title>
    <Product>MemeMomo</Product>
    <Authors>StarFall</Authors>
    <Company>StarFall</Company>
    <Description>A MemeMomo memo software</Description>
    <Copyright>StarFall</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\appicon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Strings.json" />
    <Resource Include="Assets\appicon.ico" />
    <Resource Include="Assets\appicon.png" />
    <None Include="THIRD-PARTY-NOTICES.md"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MemeMomo.Wpf.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Markdig" Version="0.41.3" />
  </ItemGroup>
</Project>
